export const sources = [
  {
    id: "verge",
    name: "The Verge",
    kind: "news",
    url: "https://www.theverge.com/rss/index.xml",
    hosts: ["theverge.com", "www.theverge.com"],
  },
  {
    id: "ars",
    name: "Ars Technica",
    kind: "news",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    hosts: ["arstechnica.com"],
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    kind: "news",
    url: "https://techcrunch.com/feed/",
    hosts: ["techcrunch.com"],
  },
  {
    id: "wired",
    name: "WIRED",
    kind: "news",
    url: "https://www.wired.com/feed/rss",
    hosts: ["www.wired.com", "wired.com"],
  },
  {
    id: "mkbhd",
    name: "Marques Brownlee",
    kind: "videos",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ",
    channel: "UCBJycsmduvYEL83R_U4JriQ",
  },
  {
    id: "fireship",
    name: "Fireship",
    kind: "videos",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA",
    channel: "UCsBjURrPoezykLs9EqgamOA",
  },
  {
    id: "computerphile",
    name: "Computerphile",
    kind: "videos",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA",
    channel: "UC9-y-6csu5WGm29I7JiwpnA",
  },
  {
    id: "two-minute-papers",
    name: "Two Minute Papers",
    kind: "videos",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    channel: "UCbfYPyITQ-7l4upoX8nvctg",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    kind: "models",
    url: "https://openrouter.ai/api/v1/models",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    kind: "trending",
    url: "https://huggingface.co/api/models?sort=trendingScore&limit=8",
  },
];
